spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${IDENTITY_JWKS_URI}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
quizopia:
  identity:
    security:
      signing-key:
        kid: ${IDENTITY_SIGNING_KEY_KID}
        private-key-path: ${IDENTITY_SIGNING_KEY_PRIVATE_KEY_PATH}
        public-key-path: ${IDENTITY_SIGNING_KEY_PUBLIC_KEY_PATH}
      authorization-server:
        enabled: ${IDENTITY_AUTHORIZATION_SERVER_ENABLED:false}
        issuer: ${IDENTITY_AUTHORIZATION_SERVER_ISSUER:}
        service-access-token-ttl: ${IDENTITY_AUTHORIZATION_SERVER_SERVICE_ACCESS_TOKEN_TTL:}
        user-access-token-ttl: ${IDENTITY_AUTHORIZATION_SERVER_USER_ACCESS_TOKEN_TTL:}
logging:
  structured:
    format:
      console: ecs
